name: tekartik_android_utils
version: 0.6.6
description: Android utilities
publish_to: none
environment:
  sdk: ^3.9.0
dependencies:
  dev_build: ">=1.1.3+1"
  intl: ">=0.18.0"
  args: ">=2.6.0"
  path: ">=1.9.0"
  fs_shim: ">=2.3.3+1"

  process_run: ">=1.2.1+1"
  glob: any
  xml: ">=6.5.0"
  tekartik_cmd_tools:
    git:
      url: https://github.com/tekartikprj/io_tools
      path: packages/cmd_tools
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_dev_menu
  tekartik_io_utils:
    git: https://github.com/tekartik/io_utils.dart
  tekartik_common_utils:
    git: https://github.com/tekartik/common_utils.dart


dev_dependencies:
  test: ">=1.24.0"
  tekartik_app_date:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_date
  tekartik_ci:
    git:
      url: https://github.com/tekartik/ci.dart
      path: ci
dependency_overrides:
#  fs_shim:
#    path: ../fs_shim.dart
#  tekartik_build_utils:
#    path: ../build_utils.dart
#  tekartik_io_auth_utils:
#    path: ../io_auth_utils.dart
# tekartik_cmd_utils:
#   path: ../cmd_utils.dart
